### ISSUE TITLE
Failing test in `BleepsDAOGovernor`: `TransactionExecutionError: invalid sender address, address is not EOA`

### ISSUE THREAD

**Issue by cameel** [wighawag/bleeps#2]
Hello again. Today bleeps tests started failing for me with the following error:
```
     TransactionExecutionError: invalid sender address, address is not EOA (EIP-3607)
```
It started happening in my test that injects the latest compiler and is still at the commit tagged `bleeps_migrations` but looks like it's reproducible on `main` too (see the repro below). I'm not sure why it's only failing now but I suspect that some incompatibility with a recently updated dependency. It does not seem to be Hardhat though.

The failure happens on this line:
```
await waitFor(BleepsDAOAccount.connect(signer).grantRole(proposerRole, users[0].address));
```

This is not the only test that does this but it's the only one that shows up in the output. For example `cannot change proposer once immortalised` fails too when I run it independently. I think the other tests just do not run when the one above fails.

### How to reproduce
```bash
git clone https://github.com/wighawag/bleeps
cd bleeps/common-lib/
npm install
npm run build
cd ../contracts
sed -i 's|"bleeps-common": "workspace:\*",|"bleeps-common": "file:../common-lib/",|g' package.json
npm install npm-run-all
npm install
npm run test
```

Failing test output:
```
  85 passing (53s)
  1 failing

  1) BleepsDAOGovernor
       BleepsDAOAccount can change its own proposer:
     TransactionExecutionError: invalid sender address, address is not EOA (EIP-3607) (vm hf=arrowGlacier -> block number=26 hash=0xf7ff66ea7313853984958814449cb556336b015d8e3dc6c3bc9fac2a50fca68f hf=arrowGlacier baseFeePerGas=0 txs=0 uncles=0 -> tx type=2 hash=0xfe7f14e51f518665213913c8fa815e2fde87891167b95c148c2d9deed588f5b6 nonce=1 value=0 signed=true hf=arrowGlacier maxFeePerGas=1000000000 maxPriorityFeePerGas=1000000000)
      at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:471:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:536:9)
      at processTimers (node:internal/timers:510:7)
      at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1496:18)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by wighawag** [comment]
closing as we made a refactor
